export const ADD_INTERVIEW = 'ADD_INTERVIEW';
export const UPDATE_INDEX = 'UPDATE_INDEX';
export const UPDATE_INTERVIEW = 'UPDATE_INTERVIEW';
export const DELETE_INTERVIEW = 'DELETE_INTERVIEW';
export const COMPLETE_INTERVIEW = 'COMPLETE_INTERVIEW';
